version: '2'
services:
  
  app:
    container_name: nbaServer
    restart: always
    build:
      context: . 
      dockerfile: server.Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'NBA'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'