version: '3'
services:

  app:
    container_name: library
    restart: always
    build:
      context: . 
      dockerfile: server.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  
  mongo-seed:
    
      build:
        context: .  
        dockerfile: seed.Dockerfile
      links:
        - mongodb