version: '3'
services:

  app:
    container_name: pcFootball
    restart: always
    build:
      context: . 
      dockerfile: server.dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  
  mongo-seedteam:
    
      build:
        context: .  
        dockerfile: seeds-players.dockerfile
      links:
        - mongodb